name: Lint Open API and Publish

on:
  pull_request:
    branches:
      - main

jobs:
  api-linting:
    name: Run Spectral
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
      # Run Spectral
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: "docs/*.yaml"

  generate-site:
    name: Generate API reference
    runs-on: ubuntu-latest
    needs: api-linting
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate API Docs
        run: npx @redocly/cli build-docs docs/docs-automation/openapi.yaml -o docs/docs-automation/openapi.html


